[env:m5stack-core-esp32-16M]
platform = espressif32@6.10.0
board = m5stack-core-esp32-16M
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM16
monitor_port = COM16
board_build.partitions = partition_3M_app.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 3145728

; 1. Pull the custom framework package with integrated Bluepad32 support
platform_packages = 
    framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip

; 2. Clean up the library dependencies
lib_deps = 
    M5Stack/M5Unified

[env:m5stack-core-s3]
platform = espressif32@6.10.0
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM8
monitor_port = COM8
board_build.partitions = partition_3M_app.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 3145728

; 1. Pull the custom framework package with integrated Bluepad32 support
platform_packages = 
    framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip

; 2. Clean up the library dependencies
lib_deps = 
    M5Stack/M5Unified
